- name: install docker from repositories
  pacman:
    name: docker
    state: latest

- name: add user to docker usergroup
  user:
    name: mingxiangchan
    groups: docker
    append: yes

- name: enable docker to start on system boot
  systemd:
    name: docker
    enabled: yes
    state: restarted
