---
- name : install fzf and ack
  become: true
  pacman:
    name: fzf
    state: latest

- name   : install neovim
  become : true
  pacman :
    name : neovim, python-neovim
    state: latest

- name   : copy vimrc
  copy   :
    src  : source_files/.ackrc
    dest : ~/.ackrc
    force: yes

- name   : copy init.vim
  copy   :
    src  : source_files/init.vim
    dest : ~/.config/nvim/init.vim
    force: yes

- name   : copy plugins.vim
  copy   :
    src  : source_files/plugins.vim
    dest : ~/.config/nvim/plugins.vim
    force: yes

- name: Install vim plugins
  command: nvim "+silent! PlugInstall!" +qall!
