---
- name   : install neovim
  pacman : 
    name : neovim, python-neovim
    state: latest

- name   : copy vimrc
  copy   : 
    src  : source_files/.vimrc
    dest : ~/.vimrc
    force: yes

- name: Create .vim folder
  file: 
    path: ~/.vim
    state: directory

- name: symlink nvim folder
  file:
    src: ~/.vim
    dest: ~/.config/nvim
    mode: 0755
    state: link

- name: symlink nvimrc
  file:
    src: ~/.vimrc
    dest: ~/.config/nvim/init.vim
    mode: 0755
    state: link


- name: Install vim plugins 
  command: nvim "+silent! PlugInstall!" +qall!