---
- name: install asdf-nodejs plugin
  raw: "~/.asdf/bin/asdf plugin-add nodejs"
  ignore_errors: true

- name: import node team's keyring
  raw: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  ignore_errors: true

- name: check installed nodejs versions
  raw: ~/.asdf/bin/asdf list nodejs
  register: installed_nodejs_versions
  ignore_errors: true

- name: install specified nodejs version
  raw: "~/.asdf/bin/asdf install nodejs {{ node_version }}"
  when: nodejs_version not in installed_nodejs_versions.stdout_lines

- name: set specified nodejs version as the global version
  raw: "~/.asdf/bin/asdf global nodejs {{ node_version }}"
