---
- name: install asdf-ruby plugin
  raw: "~/.asdf/bin/asdf plugin-add ruby"
  ignore_errors: true

- name: check installed ruby versions
  raw: ~/.asdf/bin/asdf list ruby
  register: installed_ruby_versions
  ignore_errors: true

- name: install specified ruby version
  raw: "~/.asdf/bin/asdf install ruby {{ ruby_version }}"
  when: ruby_version not in installed_ruby_versions.stdout_lines

- name: set specified ruby version as the global version
  raw: "~/.asdf/bin/asdf global ruby {{ ruby_version }}"
